name: Dungeoneers
version: ${project.version}
main: dungeoneers.Main
api-version: 1.16
authors: [Troggs, ooAddman, Caledonian_EH]
description: Dungeoneers' Dungeon Core
website: hyskies.net
commands:
  testitem:
  checkstats:
  setrarity:
  setreforge:
  setstats:
